Repository acdh-oeaw/apis-rdf-devops, pull requests merged in 2023-01, with the labels that each got.

#23 Fix: override default secret key with environment variable
  apis/settings/base.py
Labels: app-management, bug-fix

#6 Fix webpage templates
  webpage/templates/webpage/base.html
  webpage/templates/webpage/index.html
Labels: UI-UX, bug-fix

#20 Default DJANGO_SETTINGS_MODULE to ontologies local_settings
  manage.py
Labels: feature, app-management
